# configure tomcat server
server:
  port: 8888
  tomcat:
    connection-timeout: 2s # default: 20s
    keep-alive-timeout: 15s
    threads:
      max: 50 # default: 200
      min-spare: 5 # min thread always be running default: 10

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          url: https://github.com/aniljangirdev/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

